apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vmwarepopulators.forklift.konveyor.io
spec:
  group: forklift.konveyor.io
  names:
    kind: VmwarePopulator
    listKind: VmwarePopulatorList
    plural: vmwarepopulators
    singular: vmwarepopulator
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: VmwarePopulator is a specification for a VmwarePopulator resource
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string

          spec:
            description: VmwarePopulatorSpec is the spec for a VmwarePopulator resource
            properties:
              credentials:
                desription: Name of secret with password for VCenter.
                type: string
              dcPath:
                description: Data center and cluster.
                type: string
              disk:
                description: 'Disk location in format "[data_store]/path"'
                type: string
              insecure:
                description: Flag whether to use insecure SSL connections. Default false.
                type: boolean
              vcenter:
                description: Hostname or IP of VCenter and optionally followed by colon and port number.
                type: string
            required:
            - credentials
            - dcPath
            - disk
            - vcenter
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
