apiVersion: v1
kind: Namespace
metadata:
  name: vmware-populator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vmware-populator-account
  namespace: vmware-populator
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vmware-populator-role
rules:
  - apiGroups: [""]
    resources: [persistentvolumes]
    verbs: [get, list, watch, patch]
  - apiGroups: [""]
    resources: [persistentvolumeclaims]
    verbs: [get, list, watch, patch, create, delete]
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch, create, delete]
  - apiGroups: [storage.k8s.io]
    resources: [storageclasses]
    verbs: [get, list, watch]
  - apiGroups: [forklift.konveyor.io]
    resources: [vmwarepopulators]
    verbs: [get, list, watch]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vmware-populator-binding
subjects:
  - kind: ServiceAccount
    name: vmware-populator-account
    namespace: vmware-populator
roleRef:
  kind: ClusterRole
  name: vmware-populator-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: vmware-populator
  namespace: vmware-populator
spec:
  selector:
    matchLabels:
      app: vmware-populator
  template:
    metadata:
      labels:
        app: vmware-populator
    spec:
      serviceAccount: vmware-populator-account
      containers:
        - name: controller
          image: image-registry.openshift-image-registry.svc:5000/vmware-populator/vmware-populator:v0.1
          imagePullPolicy: IfNotPresent
          args:
            - --mode=controller
            - --namespace=vmware-populator
            - --image-name=image-registry.openshift-image-registry.svc:5000/vmware-populator/vmware-populator:v0.1
            - --http-endpoint=:8080
          ports:
            - containerPort: 8080
              name: http-endpoint
              protocol: TCP
---
kind: VolumePopulator
apiVersion: populator.storage.k8s.io/v1beta1
metadata:
  name: vmware-populator
sourceKind:
  group: forklift.konveyor.io
  kind: VmwarePopulator
